apiVersion: v1
kind: Service
metadata:
  name: muchtodo-backend
  namespace: muchtodo
  labels:
    app: muchtodo-backend
    component: backend
spec:
  selector:
    app: muchtodo-backend
    component: backend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
